### ISSUE TITLE
support for free google colab users would be greatly appreciated 

### ISSUE THREAD

**Issue by faisalhr1997** [ddPn08/Lsmith#28]

**Comment by fkunn1326** [comment]
Unofficially, a Notebook for running lsmith in colab can be found here.
https://github.com/junjuice/Lsmith-colab

**Comment by faisalhr1997** [comment]
> Unofficially, a Notebook for running lsmith in colab can be found here. https://github.com/junjuice/Lsmith-colab

Have you tried it? 
For me. Builing model either crashes colab or run out of memory or OSError: fp16 is not a valid git identifier.

**Comment by fkunn1326** [comment]
![image](https://user-images.githubusercontent.com/92153597/218022611-465c5b39-65c2-47a2-a184-42adc5dde979.png)
I could build by trying multiple times using this setting.

![image](https://user-images.githubusercontent.com/92153597/218023721-f83de91c-2f4e-4bc4-a23b-c5b6d2462075.png)
![image](https://user-images.githubusercontent.com/92153597/218023751-25e55f8a-f39c-4702-a440-8bfbfe44eefa.png)
