### ISSUE TITLE
生成する際にバッチ処理することは可能ですか？

### ISSUE THREAD

**Issue by coronet1127** [ddPn08/Lsmith#31]

**Comment by ddPn08** [comment]
Batch countが同時生成枚数になります。Batch sizeに関しては後々対応予定です。

**Comment by coronet1127** [comment]
返答ありがとうございます。
バッチサイズを変更することによって生成スピードは上がりますか？
使用GPUはRTX4090です。

もし、上がるのならば対応してくださるととてもとても助かります。
