### ISSUE TITLE
”Build” failed when empty "Model ID"

### ISSUE THREAD

**Issue by jonigata** [ddPn08/Lsmith#5]
if this form is emtpy, it causes internal server error.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/128374/216826398-2d2cd387-0d6e-49bd-92ee-92838cff7e78.png">

It requires this to progress.
<img width="517" alt="image" src="https://user-images.githubusercontent.com/128374/216826475-8968e880-497b-4a9c-befa-9bdb4e384eff.png">

**Comment by ddPn08** [comment]
Fixed in this commit.
https://github.com/ddPn08/Lsmith/commit/9f31565ff35620883f3c9f793782a3c2c2ff0e7d
