### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by ddPn08** [ddPn08/Lsmith#9]
Currently, there is no established means to build TensorRT OSS on Windows, and it is not supported.

**Comment by ddPn08** [comment]
Excellent work by @fkunn1326 confirmed working on windows.

**Comment by uvarient** [comment]
Am I'm new to this I appreciate this 
I don't know what to do

CANCELED [frontend 3/5] RUN apk update && apk add git && apk add git                                         9.6s
------
 > [main 2/8] RUN apt update && apt upgrade -y     && apt install software-properties-common -y     && add-apt-repository --yes ppa:deadsnakes/ppa:

**Comment by ddPn08** [comment]
@uvarient Could you please open a new issue and give us the details of the issue?

**Comment by ddPn08** [comment]
Supported Windows. You can start it by following the instructions in the readme.
